<a href="https://colab.research.google.com/github/mazarrazi/notes_code_log/blob/main/NumPyBasicsW3S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Chapter 1 NumPy basics


In [ ]:
# NumPy (Numerical Python) is used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why use NumPy?
#  In Python we have lists that serve the purpose of arrays, but they are slow to process.
#  NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

#  The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
#  Arrays are very frequently used in data science, where speed and resources are very important.

# Why is NumPy Faster Than Lists?
#  NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

#  This behavior is called locality of reference in computer science.

#  This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.


#  While they might look similar when printed, NumPy arrays and Python lists/tuples are different in terms of their capabilities and how they behave in mathematical operations.



In [ ]:
# 1 Creating Arrays

# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.


In [ ]:
# 1.1 Creating a NumPy ndarray Object

import numpy as np

arr = np.array([1,2,3,4,5])  # List ndarray

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array((1,2,3,4,5))  # Tuple ndarray
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# In NumPy, whether you create an ndarray from a list or a tuple,
# the output will be displayed with square brackets.
# NumPy does not differentiate between lists and tuples when displaying ndarrays, and both are represented using square brackets.


# while displaying no differences but,

# A NumPy list is a mutable object, meaning that its elements can be changed after it is created.
#  A tuple, on the other hand, is an immutable object, meaning that its elements cannot be changed after it is created.

# NumPy lists are typically used to store data that needs to be modified frequently, such as a list of numbers that is being sorted or a list of strings that is being filtered.
#  Tuples, on the other hand, are typically used to store data that does not need to be modified, such as a list of constants or a list of coordinates.

# In addition to these differences in mutability, there are also some differences in how NumPy lists and tuples are stored in memory.
# NumPy lists are stored in a contiguous block of memory, while tuples are stored in a list of pointers to the objects that they contain. This difference in storage can affect the speed with which NumPy lists and tuples can be accessed.

In [ ]:
# 1.2  Dimensions in Arrays

#  A dimension in arrays is one level of array depth (nested arrays).
#  nested array: are arrays that have arrays as their elements.


# 1 -- 0d

# [1, 2, 3]  -- 1d

# [[1, 2, 3], [1, 2, 3]]  -- 2d

# [[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]  -- 3d



In [ ]:
# 1.2.1  0-D arrays

#  0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

arr = np.array(42)

print(arr)

42


In [ ]:
# 1.2.2  1-D arrays

#  An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

arr = np.array([1,3,3,7])

print(arr)

[1 3 3 7]


In [ ]:
# 1.2.3  2-D arrays

#  An array that has 1-D arrays as its elements is called a 2-D array.
#   These are often used to represent matrix or 2nd order tensors.

#  NumPy has a whole sub module dedicated towards matrix operations called numpy.mat


arr = np.array([[1,8,8,6], [1,8,8,6]])

print(arr)

[[1 8 8 6]
 [1 8 8 6]]


In [ ]:
# 1.2.4  3-D arrays

# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#  These are often used to represent a 3rd order tensor.

arr = np.array( [[[1,2,3,4],[1,2,3,4]], [[1,2,3,4],[1,2,3,4]]] )

print(arr)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [ ]:
# 1.2.5  Checking Number of Dimensions

#  NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

c = np.array(43)

b = np.array([1,2,3])

d = np.array([[1,5,5,3], [6,8,0,9]])

a = np.array([[[1,2,3],[3,4,5]], [[5,6,7],[7,8,9]]])

print(a.ndim)  # ndim is an attribute
print(b.ndim)
print(c.ndim)
print(d.ndim)

3
1
0
2


In [ ]:
# 1.2.6  Higher Dimensional Arrays

# An array can have any number of dimensions.
# When the array is created, you can define the number of dimensions by using the ndmin argument.

arr = np.array([1,5,6,9], ndmin = 5)  # note its ndmin not ndim

print(arr)
print()

print(arr.ndim)

[[[[[1 5 6 9]]]]]

5


In [ ]:
# In this array the innermost dimension (5th dim) has 4 elements,
#  the 4th dim has 1 element that is the vector,
#  the 3rd dim has 1 element that is the matrix with the vector,
#  the 2nd dim has 1 element that is 3D array and
#  the 1st dim has 1 element that is a 4D array.


# Another way to explain the same,

# The outermost dimension (1st dim) is represented by a single pair of square brackets [ ].

# The 2nd dimension (2nd dim) contains a 3D array. This is represented by an extra pair of square brackets, [[ ]], added to the outermost dimension. So, we now have [[ ]].

# The 3rd dimension (3rd dim) contains a matrix (2D array) that has a vector (1D array) inside it. We add another pair of square brackets for the matrix, resulting in [[[ ]]].

# The 4th dimension (4th dim) contains a 3D array, which means we add another pair of square brackets to enclose it within the 3rd dimension: [[[[ ]]]].

# Finally, the innermost dimension (5th dim) contains a vector with elements [1, 5, 6, 9]. We add one more pair of square brackets to enclose it within the 4th dimension: [[[[[1 5 6 9]]]]].


# a breakdown of the dimensions:

# 1st dimension (outermost): 4D array.
# 2nd dimension: 3D array.
# 3rd dimension: Matrix (2D array) with a vector (1D array) inside.
# 4th dimension: 3D array.
# 5th dimension (innermost): Vector (1D array) with elements [1, 5, 6, 9].
# This can be a bit abstract to visualize, but it demonstrates how NumPy allows you to create multi-dimensional arrays of various shapes and sizes.


In [ ]:
# 2  Array Indexing

# As usual array elements can be accessed by referring to its index number. Index starts with 0


In [ ]:
# 2.1  Accessing Array Elements

arr = np.array([1,2,3,4,5])

print(arr[0])
print()

print(arr[2])

1

3


In [ ]:
# 2.2  Accessing array elements and Adding them

arr = np.array([1,2,3,4,5,6])

print(arr[3] + arr[5])

10


In [ ]:
# 2.3  Accessing 2-D arrays

arr = np.array([[1,2,3,4,5], [11,22,33,44,55]])

print(arr[1,1])
print()

print(arr[0,4])

22

5


In [ ]:
# 2.4  Accessing 3-D arrays

arr = np.array([[[1,2,3,4],[5,6,7,8]], [[11,22,33,44],[55,66,77,88]]])

print(arr[0,0,0])
print(arr[0,1,0])

print(arr[1,0,0])
print(arr[1,1,0])

1
5
11
55


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
# arr[0, 1, 2] prints the value 6.

# And this is why:

# The first number represents the first dimension, which contains two arrays:
# [[1, 2, 3], [4, 5, 6]]
# and:
# [[7, 8, 9], [10, 11, 12]]
# Since we selected 0, we are left with the first array:
# [[1, 2, 3], [4, 5, 6]]

# The second number represents the second dimension, which also contains two arrays:
# [1, 2, 3]
# and:
# [4, 5, 6]
# Since we selected 1, we are left with the second array:
# [4, 5, 6]

# The third number represents the third dimension, which contains three values:
# 4
# 5
# 6
# Since we selected 2, we end up with the third value:
# 6

In [ ]:
# 2.5  Negative Indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, -1])

print(arr[0, -5])

10
1


In [ ]:
# 3  Slicing

# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1


In [ ]:
# 3.1  with start & with stop

arr = np.array([0,1,2,3,4,5,6,7])

print(arr[0 : 6])
print()

print(arr[1 : 5])


[0 1 2 3 4 5]

[1 2 3 4]


In [ ]:
#  with start & without stop

arr = np.array([0,1,2,3,4,5,6,7])

print(arr[0 : ])


[0 1 2 3 4 5 6 7]


In [ ]:
#  without start & with stop

arr = np.array([0,1,2,3,4,5,6,7])

print(arr[ : 4])

[0 1 2 3]


In [ ]:
# 3.2  Negative slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3 : -1])
print()

print(arr[-1 : -3])  # cannot print in reverse
print()

print(arr[-5 : -3])
print()

print(arr[-3 : -5])  # cannot print in reverse

[5 6]

[]

[3 4]

[]


In [ ]:
# 3.3  Step

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

print(arr[0:5:2])


[0 2 4]


In [ ]:
#  Return every other

print(arr[ : : 2])

[0 2 4 6]


In [ ]:
# 3.4  Slicing 2-D Arrays

arr = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]])

print(arr[0, 1 : 5])
print()

print(arr[1, 1 : 5])

[1 2 3 4]

[ 7  8  9 10]


In [ ]:
#  same but with step

print(arr[0, 1 : 5 : 2])
print()

print(arr[1, 1 : 5 : 2])

[1 3]

[7 9]


In [ ]:
# 4  Data Types

# Data Types in Python

# By default Python have these data types:
# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


# Data Types in NumPy

# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
# Below is a list of all data types in NumPy and the characters used to represent them.
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

# For i, u, f, S and U we can define size as well.


In [ ]:
# 4.1  Checking Datatype

arr = np.array([1,2,3,4,5])

print(arr.dtype) # arr.dtype is an attribute


int64


In [ ]:
arr = np.array(['aaa', 'bbb', 'ccc', 'ddd'])

print(arr.dtype)

print()

arr = np.array(['aaa', 'bbb', 'ccc', 'dddd'])

print(arr.dtype)

print()

arr = np.array(['aaa', 'bbb', 'ccccc', 'ddd'])

print(arr.dtype)

# the dtype attribute reflects the length of the longest string in the array, padded with extra characters if needed.

# If the longest string in the array has a length of 5 characters, NumPy will ensure that all other strings in the array are padded with spaces to have a length of 5 characters as well.
#  This padding ensures that all elements of the array have consistent dimensions,
#   which is a common requirement when working with arrays of strings in numerical computing and data analysis.


<U3

<U4

<U5


In [ ]:
# 4.2  Creating Arrays With a Defined Data Type

#  We use the array() function to create arrays,
#   this function can take an optional argument: dtype
#    dtype allows us to define the expected data type of the array elements

#  For i, u, f, S and U we can define size as well.


In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype = 'S') # The 'S' dtype instructs NumPy to interpret the elements of the array as strings

print(arr)
print(arr.dtype) # each string element has max length of 1 so S1

print()

arr = np.array([11, 22, 33, 44, 55], dtype = 'S')

print(arr)
print(arr.dtype) # each string element has max length of 2 so S2

[b'1' b'2' b'3' b'4' b'5']
|S1

[b'11' b'22' b'33' b'44' b'55']
|S2


In [ ]:
# 4.2  Creating Arrays With a Defined Data Type & Defined Size

#  For i, u, f, S and U we can define size as well.

arr = np.array([1, 22, 333, 4], dtype = 'i4')  #  'i4', which stands for a 4-byte (32-bit) integer

print(arr)

print(arr.dtype)

#  even each value has less than 4 bytes they'll be printed as 4 bytes
#   1 has 1 bytes but it'll be considered as 4 bytes

[  1  22 333   4]
int32


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#  What if a Value Can Not Be Converted?

# arr = np.array(['a', '2', '3'], dtype = 'i') # A non integer string like 'a' can not be converted to integer (will raise an error)

# print(arr)

# print(arr.dtype)

# ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [ ]:
# 4.3  Converting Data Type on Existing Arrays

#  The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

#   The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
#    The data type can be specified using a string, like 'f' for float, 'i' for integer etc.
#     or you can use the data type directly like float for float and int for integer.


In [ ]:
# using .astype('i')

arr = np.array([1.1, 2.2, 3.3])

print(arr)
print(arr.dtype)

print()

arr1 = arr.astype('i') # 'i' & int are same

print(arr1)
print(arr1.dtype)

[1.1 2.2 3.3]
float64

[1 2 3]
int32


In [ ]:
# using .astype(int)

arr = np.array([1.1, 2.2, 3.3])

print(arr)
print(arr.dtype)

print()

arr1 = arr.astype(int) # 'i' & int are same

print(arr1)
print(arr1.dtype)

[1.1 2.2 3.3]
float64

[1 2 3]
int64


In [ ]:
# using .astype(bool)

arr = np.array([2, 3, 7, 0])

arr1 = arr.astype('bool')

print(arr1)
print(arr1.dtype)

[ True  True  True False]
bool


In [ ]:
# 5  NumPy Array Copy vs View

# The Difference Between Copy and View

# The main difference between a copy and a view of an array is that the copy is a new array,
#  and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect original array,
#  and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect the original array,
#  and any changes made to the original array will affect the view.

In [ ]:
# 5.1  Copy

arr = np.array([1, 2, 3, 4, 5 ])

arrcopy = arr.copy()

print(arrcopy)

[1 2 3 4 5]


In [ ]:
# 5.2  View

arr = np.array([1, 2, 3, 4, 5])

arrview = arr.view()

print(arrview)

[1 2 3 4 5]


In [ ]:
# 5.3  Making Changes in Copy

# copy won't affect original data

arr = np.array([1, 2, 3, 4, 5 ])

arrcopy = arr.copy()

arrcopy[2] = 8

print(arrcopy)
print()

print(arr)

[1 2 8 4 5]

[1 2 3 4 5]


In [ ]:
# 5.3  Making Changes in View

# View will affect original data

arr = np.array([1, 2, 3, 4, 5 ])

arrview = arr.view()

arrview[2] = 8

print(arrcopy)
print()

print(arr)

[1 2 8 4 5]

[1 2 8 4 5]


In [ ]:
# 5.4  Check if Array Owns its Data

#  As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

#   Every NumPy array has the attribute base that returns None if the array owns the data.
#    Otherwise, the base attribute refers to the original object.

arr = np.array([1, 2, 3, 4, 5])

arrcopy = arr.copy()
arrview = arr.view()

print(arrcopy.base)

print(arrview.base) # view doesn't own its data so it returns the original data


None
[1 2 3 4 5]


In [ ]:
# 6  Array Shape

# NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

# The shape attribute in NumPy is used to determine the dimensions or shape of a NumPy array.
#  It returns a tuple that specifies the number of elements along each axis (dimension) of the array.
#   The length of the tuple corresponds to the number of dimensions in the array.


In [ ]:
# 6.1  2-D array shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

#  (2, 4), which means that the array has 2 dimensions,
#   where the first dimension has 2 elements and the second has 4.


(2, 4)


In [ ]:
# 6.2  5-D array shape

arr = np.array([1,2,3,4], ndmin = 5)

print(arr)
print()

print(arr.shape)


[[[[[1 2 3 4]]]]]

(1, 1, 1, 1, 4)


In [ ]:
# What does the shape tuple represent?

# Integers at every index tells about the number of elements the corresponding dimension has.
#  In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.


In [ ]:
# 7   Array Reshaping

# Reshaping means changing the shape of an array.

# The shape of an array is the number of elements in each dimension.

# By reshaping we can add or remove dimensions or change number of elements in each dimension.


In [ ]:
# 7.1  Reshaping From 1-D to 2-D

# Converting 1-D array with 12 elements into a 2-D array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr1 = arr.reshape(4, 3)

print(arr1)

# The outermost dimension will have 4 arrays, each with 3 elements

# the product of the dimensions of the reshaped array should be equal to the product of the dimensions of the original array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 7.2  Reshaping From 1-D to 3-D

# Converting 1-D array with 12 elements into a 3-D array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr1 = arr.reshape(2, 3, 2)

print(arr1)

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# 7.3 Can we Reshape into any shape?

# Trying converting 1D array with 8 elements to a 2D array with 3 elements in each dimension

# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# arr1 = arr.reshape(3, 3) # 3x3 = 9 elements but we have only 8 elements

# print(arr1)


# We can reshape as long as the elements required for reshaping are equal in both shapes.

# We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array
#  but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [ ]:
# 7.4  Flattening the arrays

# Flattening array means converting a multidimensional array into a 1D array.
#  We can use reshape(-1) to do this.

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr1 = arr.reshape(-1)

print(arr1)

# Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel
# and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

[1 2 3 4 5 6]


In [ ]:
# 7.5  Unknown Dimension

# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr1 = arr.reshape(2, 2, -1)

print(arr1)

#  Note: We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# 7.6  Returns Copy or View?

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr1 = arr.reshape(4,2)

print(arr1)
print()

print(arr1.base)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[1 2 3 4 5 6 7 8]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(4,2).base)


[1 2 3 4 5 6 7 8]


In [ ]:
# 8  Iterating Arrays

# Iterating means going through elements one by one.
#  As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

# If we iterate on a n-D array it will go through n-1th dimension one by one.

In [ ]:
# 8.1  Iterating 1-D array

arr = np.array([1, 2, 3, 4, 5])

for z in arr:  # iterates over each element
  print(z)


1
2
3
4
5


In [ ]:
# 8.2  Iterating 2-D array

arr = np.array([[1, 2, 3], [6, 5, 4]])

for x in arr:  # iterates over rows & not elements
  print(x)

#  the loop for x in arr iterates over the rows of the 2D NumPy array arr
#   In each iteration, x represents a row of the array, so when you print x, you see the entire row as an array.

[1 2 3]
[6 5 4]


In [ ]:
# the above program iterates each row of the 2D array

# To iterate over each element one by one,

arr = np.array([[1, 2, 3], [6, 5, 4]])

for z in arr:  # iterates over rows
  for y in z:  # iterates over elements in each row
    print(y)



1
2
3
6
5
4


In [ ]:
# 8.3  Iterating 3-D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for z in arr:
  print(z)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
# the above program iterates each row

# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
# iterating over each element one by one,

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)



1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# 8.4  Iterating Arrays on each element Using nditer()


# Iterating on Each Scalar Element

#  In basic for loops,iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

#   The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# 8.5  Iterating With Different Step Size using nditer()

arr = np.array([[1, 2, 3], [4, 5, 6]])

for z in np.nditer(arr[:, ::2]):
  print(z)


1
3
4
6


In [ ]:
# 8.6  Iterating Array With Different Data Types

# We can use " op_dtypes " argument and pass it the expected datatype to change the datatype of elements while iterating.

# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action,
#  that extra space is called buffer, and in order to enable it in nditer() we pass " flags=['buffered'] "

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
  print(x)


b'1'
b'2'
b'3'


In [ ]:
# 8.7  Enumerated Iteration Using ndenumerate()

# Enumeration means mentioning sequence number of somethings one by one.

# Sometimes we require corresponding index of the element while iterating, the " ndenumerate() " method can be used for those usecases.


In [ ]:
#  Enumerating 1D arrays elements using ndenumerate()

arr = np.array([1 ,2, 3])

for index,x in np.ndenumerate(arr):
  print(index, x)


(0,) 1
(1,) 2
(2,) 3


In [ ]:
#  Enumerating 2D arrays elements using ndenumerate()

arr = np.array([[1 ,2, 3], [4, 5, 6]])

for index,x in np.ndenumerate(arr):
  print(index, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
# 9  Joining NumPy Arrays

# Joining means putting contents of two or more arrays in a single array.

#  In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

#   We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis.
#    If axis is not explicitly passed, it is taken as 0.


In [ ]:
# 9.1  Joining two 1D arrays using concatenate()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2))

print(arr3)

[1 2 3 4 5 6]


In [ ]:
# 9.2  Joining two 2D arrays using concatenate()

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[8, 9, 10], [11, 12, 13]])

arr3 = np.concatenate((arr1, arr2), axis=1)  # Horizontal Concatenation

print(arr3)

# axis=0 means Vertical Concatenation --  rows are stacked on top of each other
# axis=1 means Horizontal Concatenation -- columns are appended side by side

[[ 1  2  3  8  9 10]
 [ 4  5  6 11 12 13]]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[8, 9, 10], [11, 12, 13]])

arr3 = np.concatenate((arr1, arr2), axis=0)  # Vertical Concatenation

print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [11 12 13]]


In [ ]:
# The key difference between axis=0 and axis=1 is the direction of concatenation:

#  axis=0 (Vertical Concatenation):

#  Concatenating along axis=0 means stacking arrays vertically, i.e., rows are stacked on top of each other.
#   If you are concatenating 2D arrays, it will add rows, extending the number of rows in the resulting array.
#    For higher-dimensional arrays, it means stacking along the first axis, which is typically the rows in 2D arrays.


#  axis=1 (Horizontal Concatenation):

#  Concatenating along axis=1 means stacking arrays horizontally, i.e., columns are appended side by side.
#   If you are concatenating 2D arrays, it will add columns, extending the number of columns in the resulting array.
#    For higher-dimensional arrays, it means stacking along the second axis, which is typically the columns in 2D arrays.


In [ ]:
# 9.3  Joining Arrays Using Stack Functions i.e. np.stack

# Stacking is same as concatenation, the only difference is that stacking creates a new axis and then joining arrays along that new axis

# np.concatenate: Combines arrays along an existing axis without creating new dimensions.
# np.stack: Combines arrays along a new axis, creating an additional dimension.


arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.stack((arr1, arr2), axis=0)  # stack

print(arr3)
print()


arr4 = np.concatenate((arr1, arr2), axis=0) # concatenate

print(arr4)

# arr3 has 2D, wheras arr4 has 1D

[[ 1  2  3]
 [ 8  9 10]]

[ 1  2  3  8  9 10]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.stack((arr1, arr2), axis=1)  # stack

print(arr3)
print()


# arr4 = np.concatenate((arr1, arr2), axis=1) # concatenate

# print(arr4)

# arr3 has 2D, wheras arr4 is not possible, need 2D arrays to concatenate horizontally

[[ 1  8]
 [ 2  9]
 [ 3 10]]



In [ ]:
# 9.4  Stacking Along Rows using hstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.hstack((arr1, arr2))
print(arr3)

# looks all in one line

[ 1  2  3  8  9 10]


In [ ]:
# 9.5  Stacking Along Columns using vstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.vstack((arr2, arr1))
print(arr3)

# looks one upon one

[[ 8  9 10]
 [ 1  2  3]]


In [ ]:
# 9.6  Stacking Along Height (depth) using dstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.dstack((arr1, arr2))
print(arr3)

# looks side by side, similar to hstack() but not all in one line

[[[ 1  8]
  [ 2  9]
  [ 3 10]]]


In [ ]:
# summary of JOIN

# two ways to join,
#  1. Concatenate
#  2. stack


# In .concatenate(),
#  1.1 -- axis=0 means Vertical Concatenation - rows are stacked on top of each other
#  1.2 -- axis=1 means Horizontal Concatenation - columns are appended side by side


# In .stack(),
#  2.1 -- hstack() - Stacking Along Rows
#  2.2 -- vstack() - Stacking Along Columns
#  2.3 -- dstack() - Stacking Along Height (depth)

# note that hstack() & dstack() are similar with one difference,
#   in hstack() -- stacked next to one another in a single line/row
#   in dstack() -- stacked next to one another in multiple lines/rows


In [ ]:
# 10  Splitting NumPy Arrays

#  Splitting breaks one array into multiple whereas Joining merges multiple arrays into one

#  array_split() is used for splitting arrays
#   pass the array that need to be split and the number of splits.


In [ ]:
# 10.1  Splitting the array in 3 parts using array_split()

arr = np.array([1, 2, 3, 4, 5, 6])

arr1 = np.array_split(arr, 3)

print(arr1)

# The return value is a list containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#  If the array has less elements than required, it will adjust from the end accordingly.

arr = np.array([1, 2, 3, 4, 5, 6])

arr1 = np.array_split(arr, 4)

print(arr1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

arr1 = np.array_split(arr, 3)

print(arr1)

# Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting
#  like in example above, array_split() worked properly but split() would fail.

[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
# 10.2  Accessing the splitted arrays

# The return value of the array_split() method is an array containing each of the split as an array.

# If you split an array into 3 arrays, you can access them from the result just like any array element

arr = np.array([1, 2, 3, 4, 5, 6])

arr1 = np.array_split(arr, 3)

print(arr1)
print()

print(arr1[0])
print(arr1[1])
print(arr1[2])

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]
[3 4]
[5 6]


In [ ]:
# 10.3  Splitting 2-D arrays

# Splitting the 2-D array into three 2-D arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

arr1 = np.array_split(arr, 3)

print(arr)
print()

print(arr1)
print()

print(arr1[0])
print()
print(arr1[2])

# returns three 2-D array

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

[[1 2]
 [3 4]]

[[ 9 10]
 [11 12]]


In [ ]:
# 10.4  Splitting along the row (axis=1)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

arr1 = np.array_split(arr, 3, axis=1)

print(arr)
print()

print(arr1)
print()

print(arr1[0])
print()
print(arr1[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]]


In [ ]:
# 10.5  Using hsplit()

# arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
# arr1 = np.hsplit(arr, 3)
# print(arr1)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

arr1 = np.hsplit(arr, 3)

print(arr1)
print()

# to understand better,
print(arr1[0])
print()
print(arr1[1])
print()
print(arr1[2])

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]

[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
# Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().


In [ ]:
# 11  Searching Arrays

# You can search an array for a certain value, and return the indexes that get a match.

# Searching an array using the where() method

arr = np.array([1, 2, 3, 4, 5])

arr1 = np.where(arr == 3)

print(arr1)

(array([2]),)


In [ ]:
# 11.1

arr = np.array([3, 1, 2, 3, 7, 5, 3, 8])

arr1 = np.where(arr == 3)

print(arr1)

# means that the value 3 is present at index 0, 3 and 6.

(array([0, 3, 6]),)


In [ ]:
#  Find the indexes where the values are even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr1 = np.where(arr%2 == 0)

print(arr1)

# will show index values of the answers

(array([1, 3, 5, 7]),)


In [ ]:
#  Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr1 = np.where(arr%2 != 0)

print(arr1)

# will show index values of the answers

(array([0, 2, 4, 6]),)


In [ ]:
# 11.2  Search Sorted using searchsorted()

# There is a method called searchsorted() which performs a binary search in the array,
#  and returns the index where the specified value would be inserted to maintain the search order.

# The searchsorted() method is assumed to be used on sorted arrays.

arr = np.array([6, 7, 8, 9])

arr1 = np.searchsorted(arr, 7)

print(arr1)

# The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.
#  The number 7 should be inserted on index 1 to remain the sort order.

1


In [ ]:

arr = np.array([6, 77, 8, 9])

arr1 = np.searchsorted(arr, 77)

print(arr1)

# The method starts the search from the left and returns the index where the specified value would be inserted to maintain the search order.

# index starts at 0 so output should be 3 but why is it showing 4 ?
#   because it considers all the 4 values including 77 itself, then shows it should be placed at last which is index 4


4


In [ ]:
arr = np.array([5, 25, 6, 7, 8, 9, 10])

arr1 = np.searchsorted(arr, 25)

print(arr1)

# The method starts the search from the left and returns the index where the specified value would be inserted to maintain the search order.

# index starts at 0 so output should be 6 but why is it showing 7 ?
#   because it considers all the 7 values including 25 itself, then shows it should be placed at last which is index 7


7


In [ ]:
# 11.3  Search From the Right Side

# By default the left most index is returned, but we can give side='right' to return the right most index instead.

# Finding the indexes where the value 7 should be inserted, starting from the right:

arr = np.array([6, 7, 8, 9])

arr1 = np.searchsorted(arr, 7, side='right')

print(arr1)

# The number 7 should be inserted on index 2 to remain the sort order.

# The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

2


In [ ]:
arr = np.array([ 6, 7, 8, 9, 1, 2, 3, 4, 5])

arr1 = np.searchsorted(arr, 7, side='right')

print(arr1)

9


In [ ]:
# 11.4  Multiple Values

# To search for more than one value, use an array with the specified values.

arr = np.array([1, 3, 5, 7])

arr1 = np.searchsorted(arr, [2, 4, 6])

print(arr1)

# The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.


[1 2 3]


In [ ]:
arr = np.array([ 6, 7, 8, 9, 1, 2, 3, 4, 5])

arr1 = np.searchsorted(arr, [8, 9 ,1])

print(arr1)


[9 9 0]


In [ ]:
#  searchsorted() summary

#  it searches the whole array & returns the index where the specified value should be placed
#   when returning the index it consideres the current value position without neglecting it,
#     i.e.   5, 7, 8, 1, 3, 9  in it searchsort 5,  so now it'll include 5 also while mentioning the index in the return
#         op: 5


In [ ]:
# 12  Sorting Arrays

# Sorting is ordering the sequence

# A Sequence can be ordered by arranging numerics or alphabets in ascending or descending order

# sort() is used to sort the array


In [ ]:
# 12.1  Sorting the array containing numerics

arr = np.array([3, 5, 2, 1])

print(np.sort(arr)) # This method returns a copy of the array, leaving the original array unchanged.
print()

print(arr) # original is unaffected

[1 2 3 5]

[3 5 2 1]


In [ ]:
# 12.2  Sorting the array containing alphabets

arr = np.array(['bbb', 'ddd', 'eee', 'aaa'])

print(np.sort(arr))

['aaa' 'bbb' 'ddd' 'eee']


In [ ]:
# 12.3  Sorting the array containing boolean

arr = np.array([False, True, False, False, True, True])

print(np.sort(arr))

[False False False  True  True  True]


In [ ]:
# 12.4  Sorting a 2-D Array

# If you use the sort() method on a 2-D array, both arrays will be sorted:

arr = np.array([[9, 5, 7], [3, 7, 6]])

print(np.sort(arr))

[[5 7 9]
 [3 6 7]]


In [ ]:
# 13  Filtering Arrays



